version: "3.8"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: local-mssql
    environment:
      SA_PASSWORD: "Dev@1234"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
