version: "3.8"
services:
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: voxuy-mssql
    environment:
      SA_PASSWORD: "Develop@123"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
    volumes:
      - mssql-data:/var/opt/mssql/data

volumes:
  mssql-data:
